// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSsuozpgQ97gxsC-uflixNhcu1p3Z8znw',
    appId: '1:1077863559973:web:0780c47c075df08a8360cc',
    messagingSenderId: '1077863559973',
    projectId: 'appmess-1b730',
    authDomain: 'appmess-1b730.firebaseapp.com',
    storageBucket: 'appmess-1b730.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgZgbIbQirF1oOeWJKwJQcaXUR2oMR2Bs',
    appId: '1:1077863559973:android:0a5d004a0bf8dc158360cc',
    messagingSenderId: '1077863559973',
    projectId: 'appmess-1b730',
    storageBucket: 'appmess-1b730.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9mfCnPpr857Uvr5WdsRNdi3x4Vy1lHk',
    appId: '1:1077863559973:ios:78bff64a927d2f8b8360cc',
    messagingSenderId: '1077863559973',
    projectId: 'appmess-1b730',
    storageBucket: 'appmess-1b730.appspot.com',
    iosBundleId: 'com.example.myMess',
  );
}
