platform :ios, '13.0'

# CocoaPods analytics
install! 'cocoapods', :disable_input_output_paths => true

# Flutter-specific settings
flutter_root = File.expand_path('..', __dir__)
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  # Flutter Pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Your other pod dependencies go here
end
