platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Firebase Pods
  pod 'Firebase/Core', '~> 10.3.0'
  pod 'Firebase/Firestore', '~> 10.3.0'
  pod 'Firebase/Auth', '~> 10.3.0'
  pod 'Firebase/Messaging', '~> 10.3.0'
end

post_install do |installer|
  flutter_post_install(installer)
end

